# Generated by Django 5.1.2 on 2024-10-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='combo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.combo'),
        ),
    ]
