# Generated by Django 5.1.2 on 2024-10-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_calories_product_carbs_product_fats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='combo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.combo'),
        ),
    ]
