# Generated by Django 5.1.2 on 2024-10-24 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='combo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.combo'),
        ),
    ]
