# Generated by Django 5.1.2 on 2024-10-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_combo_quantity_remove_product_combo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
