# Generated by Django 5.1.2 on 2024-10-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_isnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='combodetails',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
