# Generated by Django 5.1.2 on 2024-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_combodetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combodetails',
            name='image',
        ),
        migrations.AddField(
            model_name='combo',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
