# Generated by Django 5.1.2 on 2024-10-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_combodetails_image_combo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combodetails',
            name='discount',
        ),
        migrations.AddField(
            model_name='combo',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
