# Generated by Django 5.1.2 on 2024-11-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_combodetails_discount_combo_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combodetails',
            name='combo',
        ),
        migrations.RemoveField(
            model_name='combodetails',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isSale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='combo',
        ),
        migrations.DeleteModel(
            name='comboDetails',
        ),
    ]
