# Generated by Django 5.1.2 on 2024-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetails',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
