# Generated by Django 5.1.2 on 2024-11-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartdetails_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartdetails',
            options={'verbose_name': 'Cart Details', 'verbose_name_plural': 'Cart Details'},
        ),
    ]
