# Generated by Django 5.1.2 on 2024-10-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.CharField(default='', max_length=250)),
                ('order_date', models.DateField(auto_now=True)),
                ('order_total', models.IntegerField(default=0)),
                ('order_status', models.BooleanField(default=False)),
                ('order_description', models.CharField(default='', max_length=250)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
    ]
