# Generated by Django 5.1.2 on 2024-11-10 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderdetails_order_delete_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(default='', max_length=250)),
                ('date', models.DateField(auto_now=True)),
                ('total', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('note', models.CharField(default='', max_length=250)),
                ('code', models.CharField(default='', max_length=250)),
                ('phone', models.CharField(default='', max_length=250)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
