# Generated by Django 5.1.2 on 2024-11-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'Order Details', 'verbose_name_plural': 'Order Details'},
        ),
    ]
